# Generated by Django 5.2.8 on 2025-11-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='comments',
            new_name='comment_count',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='likes',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='views',
            new_name='view_count',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='total_videos',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='total_views',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
